### ISSUE TITLE
Unhandled promise rejections

### ISSUE THREAD

**Issue by alohadude3** [Hermitter/BDO-Boss-Alerts#4]
(node:32598) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): DiscordAPIError: Missing Permissions
(node:32598) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

The above messages are logged in the console upon a boss spawn.

I am running this on a Linux instance on Google's Cloud Compute Engine.

**Comment by Hermitter** [comment]
It looks like your bot doesn't have permission to write in that server or text channel

**Comment by alohadude3** [comment]
The message it sends upon first connecting sends correctly. Is there some other specific permission I need to enable it to send rich embeds? I tried looking around but did not find anything.

**Comment by Hermitter** [comment]
You should be good, but I can't reproduce the errors your getting. Did you change any of the code? If not, try updating [Node ](https://github.com/creationix/nvm) and create another discord app.

**Comment by alohadude3** [comment]
No code change. What Node version are you running the bot with? I'm using v8.9.4

**Comment by Hermitter** [comment]
I've gotten it to work on v8.6.0 and v9.5.0

**Comment by alohadude3** [comment]
Do you have a way of emulating boss spawns just to make testing a bit less tedious?

**Comment by Hermitter** [comment]
` emitter.bossEvents.sendEvent("bossSpawn", bossData.kutum);`
Add this to [line 69](https://github.com/Hermitter/BDO-Boss-Alerts/blob/master/bdoBossAlert.js#L69) of bdoBossAlert.js

**Comment by alohadude3** [comment]
Ok it's resolved now, seems like just my channel permissions were a bit messed up with all the roles and category nesting.
