### ISSUE TITLE
Read-me is incorrect

### ISSUE THREAD

**Issue by Krizziebb** [Hermitter/BDO-Boss-Alerts#7]
Some people may run in to the same little bit of confusion as i did, i was getting the incorrect credentials error as i was using the Client-ID. You need to use the Bot user token, please could you change 

> "Insert your bot-id and desired text-channel-id in the config.json file"

To 

> "Insert your Bot user token and desired text-channel-id in the config.json file"

**Comment by Hermitter** [comment]
Updated the README.
